export default {
	REQUEST_SIGNIN: "REQUEST_SIGNIN",
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_FAILURE: "SIGNIN_FAILURE",

	REQUEST_SIGNUP: "REQUEST_SIGNUP",
	SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

	REQUEST_SIGNOUT: "REQUEST_SIGNOUT",
	SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",

	REQUEST_EDITUSER: "REQUEST_EDITUSER",
	EDITUSER_SUCCESS: "EDITUSER_SUCCESS",
 
	REQUEST_CHANGEPASSWORD: "REQUEST_CHANGEPASSWORD",
	CHANGEPASSWORD_SUCCESS: "CHANGEPASSWORD_SUCCESS",

	REQUEST_ADDTASK: "REQUEST_ADDTASK",
	ADDTASK_SUCCESS: "ADDTASK_SUCCESS",
	
	REQUEST_DELETEACCOUNT: "REQUEST_DELETEACCOUNT",
	DELETEACCOUNT_SUCCESS: "DELETEACCOUNT_SUCCESS"
};
